"""Pure stateless formulas for geometric algebra networks."""

from .activation import geometric_gelu, geometric_square, grade_swish
from .loss import (
    asymmetry_penalty,
    bivector_regularization,
    chamfer_distance,
    conservative_force_loss,
    geometric_mse,
    hermitian_grade_regularization,
    involution_consistency_loss,
    isometry_loss,
    physics_informed_loss,
    subspace_penalty,
)
from .orthogonality import (
    cross_grade_coupling,
    diagnostics,
    grade_energies,
    grade_masks,
    parasitic_energy,
    parasitic_ratio,
    project_to_target_grades,
    target_mask_from_grades,
)
from .products import (
    anti_commutator,
    clifford_conjugation,
    commutator,
    dual,
    embed_vector,
    geometric_product,
    grade_involution,
    grade_projection,
    inner_product,
    norm_sq,
    product,
    projected_product,
    reverse,
    wedge,
)

__all__ = [
    "geometric_gelu",
    "geometric_square",
    "grade_swish",
    "product",
    "projected_product",
    "geometric_product",
    "wedge",
    "inner_product",
    "commutator",
    "anti_commutator",
    "grade_projection",
    "reverse",
    "grade_involution",
    "clifford_conjugation",
    "dual",
    "norm_sq",
    "embed_vector",
    "geometric_mse",
    "subspace_penalty",
    "isometry_loss",
    "bivector_regularization",
    "hermitian_grade_regularization",
    "chamfer_distance",
    "conservative_force_loss",
    "physics_informed_loss",
    "asymmetry_penalty",
    "involution_consistency_loss",
    "grade_masks",
    "target_mask_from_grades",
    "parasitic_energy",
    "project_to_target_grades",
    "grade_energies",
    "parasitic_ratio",
    "cross_grade_coupling",
    "diagnostics",
]
