# clifra (C) 2026 Eunkyum Kim
# SPDX-License-Identifier: Apache-2.0

"""Pure stateless formulas for geometric algebra networks."""

from .activation import geometric_gelu, geometric_square, grade_swish
from .loss import (
    asymmetry_penalty,
    bivector_regularization,
    chamfer_distance,
    conservative_force_loss,
    geometric_mse,
    grade_energy_regularization,
    involution_consistency_loss,
    isometry_loss,
    physics_informed_loss,
    subspace_penalty,
)
from .orthogonality import (
    cross_grade_coupling,
    diagnostics,
    grade_energies,
    grade_masks,
    parasitic_energy,
    parasitic_ratio,
    project_to_target_grades,
    target_mask_from_grades,
)
from .products import (
    anti_commutator_product,
    bivector_exp,
    blade_inverse,
    blade_project,
    blade_reject,
    canonical_product_op,
    clifford_conjugation,
    commutator_product,
    embed_vector,
    geometric_product,
    grade_involution,
    grade_norms,
    grade_projection,
    left_contraction,
    multi_rotor_sandwich,
    multi_versor_action,
    paired_bivector_action,
    per_channel_sandwich,
    planned_linear_action,
    product,
    projected_product,
    pseudoscalar_product,
    reflect,
    reverse,
    right_contraction,
    sandwich_action_matrices,
    sandwich_product,
    signature_norm_squared,
    symmetric_product,
    versor_action,
    versor_product,
    wedge,
)

__all__ = [
    "geometric_gelu",
    "geometric_square",
    "grade_swish",
    "product",
    "projected_product",
    "canonical_product_op",
    "geometric_product",
    "wedge",
    "symmetric_product",
    "commutator_product",
    "anti_commutator_product",
    "left_contraction",
    "right_contraction",
    "grade_projection",
    "reverse",
    "grade_involution",
    "clifford_conjugation",
    "pseudoscalar_product",
    "signature_norm_squared",
    "bivector_exp",
    "embed_vector",
    "blade_inverse",
    "blade_project",
    "blade_reject",
    "reflect",
    "versor_product",
    "planned_linear_action",
    "sandwich_action_matrices",
    "sandwich_product",
    "per_channel_sandwich",
    "multi_rotor_sandwich",
    "versor_action",
    "multi_versor_action",
    "paired_bivector_action",
    "grade_norms",
    "geometric_mse",
    "subspace_penalty",
    "isometry_loss",
    "bivector_regularization",
    "grade_energy_regularization",
    "chamfer_distance",
    "conservative_force_loss",
    "physics_informed_loss",
    "asymmetry_penalty",
    "involution_consistency_loss",
    "grade_masks",
    "target_mask_from_grades",
    "parasitic_energy",
    "project_to_target_grades",
    "grade_energies",
    "parasitic_ratio",
    "cross_grade_coupling",
    "diagnostics",
]
