# Versor: Universal Geometric Algebra Neural Network
# Copyright (C) 2026 Eunkyum Kim <nemonanconcode@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#

"""Static planning policy for layout fallback and plan-cost diagnostics."""

from __future__ import annotations

import warnings
from dataclasses import dataclass
from typing import Optional

from clifra.core.foundation.basis import basis_count_for_grades, expand_output_grades, normalize_grades
from clifra.core.foundation.layout import AlgebraSpec, GradeLayout

FULL_LAYOUT_WARN_N = 8
FULL_LAYOUT_MAX_N = 12


@dataclass(frozen=True)
class PlanningLimits:
    """Static cost limits for planned grade execution.

    ``max_lanes`` protects compact tensor width. ``max_pairs`` protects the
    gather/reduce interaction count generated by a bilinear product plan.
    """

    warn_lanes: int = 2048
    max_lanes: int = 4096
    warn_pairs: int = 1_000_000
    max_pairs: int = 8_000_000


@dataclass(frozen=True)
class PlanCost:
    """Static cost summary for a layout or planned operation."""

    spec: AlgebraSpec
    kind: str
    op: str
    left_lanes: int = 0
    right_lanes: int = 0
    output_lanes: int = 0
    pair_count: int = 0
    input_grades: tuple[int, ...] = ()
    left_grades: tuple[int, ...] = ()
    right_grades: tuple[int, ...] = ()
    output_grades: tuple[int, ...] = ()

    @property
    def max_lanes(self) -> int:
        return max(self.left_lanes, self.right_lanes, self.output_lanes)


DEFAULT_PLANNING_LIMITS = PlanningLimits()
_WARNED_FULL_LAYOUT_SIGNATURES: set[tuple[int, int, int]] = set()
_WARNED_PLAN_COSTS: set[tuple[object, ...]] = set()


def planning_limits_for(algebra) -> PlanningLimits:
    """Return per-algebra planning limits, falling back to defaults."""
    return getattr(algebra, "planning_limits", DEFAULT_PLANNING_LIMITS)


def full_layout_allowed(algebra, spec: AlgebraSpec) -> bool:
    """Return whether implicit full-layout planning is enabled for this algebra."""
    return bool(getattr(algebra, "allow_full_layout_products", False)) and spec.n <= FULL_LAYOUT_MAX_N


def warn_full_layout_fallback(algebra) -> None:
    """Warn once per signature when implicit full layout is used at n>=8."""
    if getattr(algebra, "n", 0) < FULL_LAYOUT_WARN_N:
        return
    signature = (int(algebra.p), int(algebra.q), int(algebra.r))
    if signature in _WARNED_FULL_LAYOUT_SIGNATURES:
        return
    _WARNED_FULL_LAYOUT_SIGNATURES.add(signature)
    warnings.warn(
        f"Using implicit full Cl({algebra.p},{algebra.q},{algebra.r}) layout at n={algebra.n}. "
        "Declare active grades or default_grades to avoid full-layout planning.",
        RuntimeWarning,
        stacklevel=3,
    )


def validate_layout_cost(algebra, layout: GradeLayout, *, role: str = "layout") -> GradeLayout:
    """Validate one compact layout against static lane limits."""
    cost = PlanCost(
        spec=layout.spec,
        kind="layout",
        op=role,
        output_lanes=layout.dim,
        output_grades=layout.grades,
    )
    validate_plan_cost(algebra, cost)
    return layout


def validate_grades_cost(algebra, spec: AlgebraSpec, grades, *, role: str = "layout") -> tuple[int, ...]:
    """Validate a grade set before materializing its basis indices."""
    normalized = normalize_grades(grades, spec.n)
    cost = PlanCost(
        spec=spec,
        kind="layout",
        op=role,
        output_lanes=basis_count_for_grades(spec.n, normalized),
        output_grades=normalized,
    )
    validate_plan_cost(algebra, cost)
    return normalized


def validate_product_grades_cost(
    algebra,
    spec: AlgebraSpec,
    *,
    op: str,
    left_grades,
    right_grades,
    output_grades=None,
) -> tuple[tuple[int, ...], tuple[int, ...], tuple[int, ...]]:
    """Validate product grade sets before materializing layouts."""
    left = normalize_grades(left_grades, spec.n, name="left_grades")
    right = normalize_grades(right_grades, spec.n, name="right_grades")
    output = (
        expand_output_grades(left, right, spec.n, op=op)
        if output_grades is None
        else normalize_grades(output_grades, spec.n, name="output_grades")
    )
    left_lanes = basis_count_for_grades(spec.n, left)
    right_lanes = basis_count_for_grades(spec.n, right)
    output_lanes = basis_count_for_grades(spec.n, output)
    validate_plan_cost(
        algebra,
        PlanCost(
            spec=spec,
            kind="product",
            op=str(op),
            left_lanes=left_lanes,
            right_lanes=right_lanes,
            output_lanes=output_lanes,
            pair_count=left_lanes * right_lanes,
            left_grades=left,
            right_grades=right,
            output_grades=output,
        ),
    )
    return left, right, output


def product_plan_cost(request) -> PlanCost:
    """Return static cost summary for a product request."""
    return PlanCost(
        spec=request.spec,
        kind="product",
        op=request.op,
        left_lanes=request.left_layout.dim,
        right_lanes=request.right_layout.dim,
        output_lanes=request.output_layout.dim,
        pair_count=request.left_layout.dim * request.right_layout.dim,
        left_grades=request.left_grades,
        right_grades=request.right_grades,
        output_grades=request.output_grades,
    )


def unary_plan_cost(request) -> PlanCost:
    """Return static cost summary for a unary request."""
    return PlanCost(
        spec=request.spec,
        kind="unary",
        op=request.op,
        left_lanes=request.input_layout.dim,
        output_lanes=request.output_layout.dim,
        input_grades=request.input_grades,
        output_grades=request.output_grades,
    )


def validate_product_request(algebra, request) -> None:
    """Validate product request static cost."""
    validate_plan_cost(algebra, product_plan_cost(request))


def validate_unary_request(algebra, request) -> None:
    """Validate unary request static cost."""
    validate_plan_cost(algebra, unary_plan_cost(request))


def validate_plan_cost(algebra, cost: PlanCost, *, limits: Optional[PlanningLimits] = None) -> None:
    """Raise on excessive static cost and warn once near configured limits."""
    limits = planning_limits_for(algebra) if limits is None else limits
    errors = []
    if cost.max_lanes > limits.max_lanes:
        errors.append(f"active lanes {cost.max_lanes} exceed max_lanes={limits.max_lanes}")
    if cost.pair_count > limits.max_pairs:
        errors.append(f"basis interactions {cost.pair_count} exceed max_pairs={limits.max_pairs}")
    if errors:
        detail = "; ".join(errors)
        raise ValueError(f"Static {cost.kind} plan for {cost.op} is too large: {detail}. Declare fewer grades.")

    warnings_to_emit = []
    if cost.max_lanes >= limits.warn_lanes:
        warnings_to_emit.append(f"active lanes {cost.max_lanes} are near max_lanes={limits.max_lanes}")
    if cost.pair_count >= limits.warn_pairs:
        warnings_to_emit.append(f"basis interactions {cost.pair_count} are near max_pairs={limits.max_pairs}")
    if warnings_to_emit:
        _warn_plan_cost_once(cost, "; ".join(warnings_to_emit))


def _warn_plan_cost_once(cost: PlanCost, detail: str) -> None:
    key = (
        cost.spec,
        cost.kind,
        cost.op,
        cost.input_grades,
        cost.left_grades,
        cost.right_grades,
        cost.output_grades,
        cost.max_lanes,
        cost.pair_count,
    )
    if key in _WARNED_PLAN_COSTS:
        return
    _WARNED_PLAN_COSTS.add(key)
    warnings.warn(
        f"Static {cost.kind} plan for {cost.op} is large: {detail}.",
        RuntimeWarning,
        stacklevel=3,
    )
