# clifra (C) 2026 Eunkyum Kim
# SPDX-License-Identifier: Apache-2.0


"""Static planning policy for plan-cost diagnostics."""

from __future__ import annotations

import warnings
from dataclasses import dataclass
from typing import Optional

import torch

from clifra.core.foundation.basis import basis_count_for_grades, expand_output_grades, normalize_grades
from clifra.core.foundation.layout import AlgebraSpec, GradeLayout
from clifra.core.planning.tree import GradePlanTree, build_grade_plan_tree

FULL_TABLE_AUTO_MAX_N = 8
FULL_TABLE_EXPLICIT_MAX_N = 12


@dataclass(frozen=True)
class PlanningLimits:
    """Static cost limits for planned grade execution.

    ``max_lanes`` protects compact tensor width. ``max_pairs`` protects the
    gather/reduce interaction count generated by a bilinear product plan.
    """

    warn_lanes: int = 2048
    max_lanes: int = 4096
    warn_pairs: int = 1_000_000
    max_pairs: int = 8_000_000


@dataclass(frozen=True)
class PlanCost:
    """Static cost summary for a layout or planned operation."""

    spec: AlgebraSpec
    kind: str
    op: str
    left_lanes: int = 0
    right_lanes: int = 0
    output_lanes: int = 0
    pair_count: int = 0
    input_grades: tuple[int, ...] = ()
    left_grades: tuple[int, ...] = ()
    right_grades: tuple[int, ...] = ()
    output_grades: tuple[int, ...] = ()

    @property
    def max_lanes(self) -> int:
        """Return the largest lane width among the planned operands."""
        return max(self.left_lanes, self.right_lanes, self.output_lanes)


@dataclass(frozen=True)
class ProductExecutionPolicy:
    """Flexible static cost model for product executor selection.

    The model is deliberately equation-based. Benchmarks can validate and tune
    these weights, but product dispatch itself only depends on declared layouts,
    grade-tree metadata, dtype, and backend.
    """

    cpu_full_table_pair_weight: float = 1.0
    cpu_sparse_pair_weight: float = 1.5
    cpu_full_table_path_weight: float = 0.0
    cpu_sparse_path_weight: float = 5.0
    cpu_full_table_output_weight: float = 0.05
    cpu_sparse_output_weight: float = 0.05
    mps_full_table_pair_weight: float = 1.2
    mps_sparse_pair_weight: float = 0.9
    mps_full_table_path_weight: float = 0.0
    mps_sparse_path_weight: float = 1.0
    mps_full_table_output_weight: float = 0.03
    mps_sparse_output_weight: float = 0.03
    default_full_table_pair_weight: float = 1.0
    default_sparse_pair_weight: float = 1.25
    default_full_table_path_weight: float = 0.0
    default_sparse_path_weight: float = 3.0
    default_full_table_output_weight: float = 0.05
    default_sparse_output_weight: float = 0.05
    memory_cost_unit_bytes: int = 4096
    full_table_memory_weight: float = 1.0
    sparse_memory_weight: float = 1.0
    full_table_max_lanes: int = 4096


@dataclass(frozen=True)
class ProductExecutorCost:
    """Static executor-selection score for one declared product request."""

    executor_family: str
    full_table_score: float
    sparse_score: float
    full_table_pair_count: int
    sparse_estimated_pairs: int
    full_table_estimated_bytes: int
    sparse_estimated_bytes: int
    path_count: int
    backend: str
    tree: GradePlanTree

    @property
    def selected_score(self) -> float:
        """Return the score for the selected executor family."""
        return self.full_table_score if self.executor_family == "full_table" else self.sparse_score


DEFAULT_PLANNING_LIMITS = PlanningLimits()
DEFAULT_PRODUCT_EXECUTION_POLICY = ProductExecutionPolicy()
_WARNED_PLAN_COSTS: set[tuple[object, ...]] = set()


def planning_limits_for(algebra) -> PlanningLimits:
    """Return per-algebra planning limits, falling back to defaults."""
    return getattr(algebra, "planning_limits", DEFAULT_PLANNING_LIMITS)


def product_execution_policy_for(algebra) -> ProductExecutionPolicy:
    """Return per-algebra product executor policy, falling back to defaults."""
    return getattr(algebra, "product_execution_policy", DEFAULT_PRODUCT_EXECUTION_POLICY)


def estimate_product_executor_cost(
    algebra,
    *,
    op: str,
    left_layout: GradeLayout,
    right_layout: GradeLayout,
    output_layout: GradeLayout,
    dtype: torch.dtype,
    device,
    policy: Optional[ProductExecutionPolicy] = None,
) -> ProductExecutorCost:
    """Return static product executor scores and the selected family.

    Sparse execution is always selected for non-full layouts because the
    full-table executor is defined only for canonical full-lane input and
    output. Full-layout requests compare full-table and sparse grade-tree
    equations.
    """
    policy = product_execution_policy_for(algebra) if policy is None else policy
    tree = build_grade_plan_tree(
        left_layout.spec,
        op=op,
        left_grades=left_layout.grades,
        right_grades=right_layout.grades,
        output_grades=output_layout.grades,
    )
    backend = _device_backend(device)
    dtype_bytes = _dtype_bytes(dtype)
    full_table_pair_count = left_layout.dim * right_layout.dim
    sparse_estimated_pairs = tree.estimated_pairs
    full_table_estimated_bytes = full_table_pair_count * (8 + dtype_bytes)
    sparse_estimated_bytes = sparse_estimated_pairs * (24 + dtype_bytes)

    full_table_score = _executor_score(
        pair_count=full_table_pair_count,
        path_count=tree.path_count,
        output_lanes=output_layout.dim,
        estimated_bytes=full_table_estimated_bytes,
        pair_weight=_weight(policy, backend, "full_table_pair"),
        path_weight=_weight(policy, backend, "full_table_path"),
        output_weight=_weight(policy, backend, "full_table_output"),
        memory_weight=policy.full_table_memory_weight,
        memory_cost_unit_bytes=policy.memory_cost_unit_bytes,
    )
    sparse_score = _executor_score(
        pair_count=sparse_estimated_pairs,
        path_count=tree.path_count,
        output_lanes=output_layout.dim,
        estimated_bytes=sparse_estimated_bytes,
        pair_weight=_weight(policy, backend, "sparse_pair"),
        path_weight=_weight(policy, backend, "sparse_path"),
        output_weight=_weight(policy, backend, "sparse_output"),
        memory_weight=policy.sparse_memory_weight,
        memory_cost_unit_bytes=policy.memory_cost_unit_bytes,
    )
    full_grades = tuple(range(left_layout.spec.n + 1))
    full_table_supported = (
        left_layout.grades == full_grades
        and right_layout.grades == full_grades
        and output_layout.grades == full_grades
        and output_layout.dim <= policy.full_table_max_lanes
    )
    family = "full_table" if full_table_supported and full_table_score <= sparse_score else "sparse"
    return ProductExecutorCost(
        executor_family=family,
        full_table_score=full_table_score if full_table_supported else float("inf"),
        sparse_score=sparse_score,
        full_table_pair_count=full_table_pair_count,
        sparse_estimated_pairs=sparse_estimated_pairs,
        full_table_estimated_bytes=full_table_estimated_bytes,
        sparse_estimated_bytes=sparse_estimated_bytes,
        path_count=tree.path_count,
        backend=backend,
        tree=tree,
    )


def validate_layout_cost(algebra, layout: GradeLayout, *, role: str = "layout") -> GradeLayout:
    """Validate one compact layout against static lane limits."""
    cost = PlanCost(
        spec=layout.spec,
        kind="layout",
        op=role,
        output_lanes=layout.dim,
        output_grades=layout.grades,
    )
    validate_plan_cost(algebra, cost)
    return layout


def validate_grades_cost(algebra, spec: AlgebraSpec, grades, *, role: str = "layout") -> tuple[int, ...]:
    """Validate a grade set before materializing its basis indices."""
    normalized = normalize_grades(grades, spec.n)
    cost = PlanCost(
        spec=spec,
        kind="layout",
        op=role,
        output_lanes=basis_count_for_grades(spec.n, normalized),
        output_grades=normalized,
    )
    validate_plan_cost(algebra, cost)
    return normalized


def validate_product_grades_cost(
    algebra,
    spec: AlgebraSpec,
    *,
    op: str,
    left_grades,
    right_grades,
    output_grades=None,
) -> tuple[tuple[int, ...], tuple[int, ...], tuple[int, ...]]:
    """Validate product grade sets before materializing layouts."""
    left = normalize_grades(left_grades, spec.n, name="left_grades")
    right = normalize_grades(right_grades, spec.n, name="right_grades")
    output = (
        expand_output_grades(left, right, spec.n, op=op)
        if output_grades is None
        else normalize_grades(output_grades, spec.n, name="output_grades")
    )
    left_lanes = basis_count_for_grades(spec.n, left)
    right_lanes = basis_count_for_grades(spec.n, right)
    output_lanes = basis_count_for_grades(spec.n, output)
    validate_plan_cost(
        algebra,
        PlanCost(
            spec=spec,
            kind="product",
            op=str(op),
            left_lanes=left_lanes,
            right_lanes=right_lanes,
            output_lanes=output_lanes,
            pair_count=left_lanes * right_lanes,
            left_grades=left,
            right_grades=right,
            output_grades=output,
        ),
    )
    return left, right, output


def product_plan_cost(request) -> PlanCost:
    """Return static cost summary for a product request."""
    return PlanCost(
        spec=request.spec,
        kind="product",
        op=request.op,
        left_lanes=request.left_layout.dim,
        right_lanes=request.right_layout.dim,
        output_lanes=request.output_layout.dim,
        pair_count=request.left_layout.dim * request.right_layout.dim,
        left_grades=request.left_grades,
        right_grades=request.right_grades,
        output_grades=request.output_grades,
    )


def unary_plan_cost(request) -> PlanCost:
    """Return static cost summary for a unary request."""
    return PlanCost(
        spec=request.spec,
        kind="unary",
        op=request.op,
        left_lanes=request.input_layout.dim,
        output_lanes=request.output_layout.dim,
        input_grades=request.input_grades,
        output_grades=request.output_grades,
    )


def validate_product_request(algebra, request) -> None:
    """Validate product request static cost."""
    validate_plan_cost(algebra, product_plan_cost(request))


def validate_unary_request(algebra, request) -> None:
    """Validate unary request static cost."""
    validate_plan_cost(algebra, unary_plan_cost(request))


def validate_plan_cost(algebra, cost: PlanCost, *, limits: Optional[PlanningLimits] = None) -> None:
    """Raise on excessive static cost and warn once near configured limits."""
    limits = planning_limits_for(algebra) if limits is None else limits
    errors = []
    if cost.max_lanes > limits.max_lanes:
        errors.append(f"compact lanes {cost.max_lanes} exceed max_lanes={limits.max_lanes}")
    if cost.pair_count > limits.max_pairs:
        errors.append(f"basis interactions {cost.pair_count} exceed max_pairs={limits.max_pairs}")
    if errors:
        detail = "; ".join(errors)
        raise ValueError(f"Static {cost.kind} plan for {cost.op} is too large: {detail}. Declare fewer grades.")

    warnings_to_emit = []
    if cost.max_lanes >= limits.warn_lanes:
        warnings_to_emit.append(f"compact lanes {cost.max_lanes} are near max_lanes={limits.max_lanes}")
    if cost.pair_count >= limits.warn_pairs:
        warnings_to_emit.append(f"basis interactions {cost.pair_count} are near max_pairs={limits.max_pairs}")
    if warnings_to_emit:
        _warn_plan_cost_once(cost, "; ".join(warnings_to_emit))


def _executor_score(
    *,
    pair_count: int,
    path_count: int,
    output_lanes: int,
    estimated_bytes: int,
    pair_weight: float,
    path_weight: float,
    output_weight: float,
    memory_weight: float,
    memory_cost_unit_bytes: int,
) -> float:
    memory_units = estimated_bytes / max(int(memory_cost_unit_bytes), 1)
    return (
        float(pair_count) * float(pair_weight)
        + float(path_count) * float(path_weight)
        + float(output_lanes) * float(output_weight)
        + float(memory_units) * float(memory_weight)
    )


def _device_backend(device) -> str:
    if device is None:
        return "cpu"
    text = str(device)
    if text.startswith("mps"):
        return "mps"
    if text.startswith("cuda"):
        return "cuda"
    if text.startswith("cpu"):
        return "cpu"
    return "default"


def _dtype_bytes(dtype: torch.dtype) -> int:
    return torch.empty((), dtype=dtype).element_size()


def _weight(policy: ProductExecutionPolicy, backend: str, name: str) -> float:
    if backend == "cpu":
        return float(getattr(policy, f"cpu_{name}_weight"))
    if backend == "mps":
        return float(getattr(policy, f"mps_{name}_weight"))
    return float(getattr(policy, f"default_{name}_weight"))


def _warn_plan_cost_once(cost: PlanCost, detail: str) -> None:
    key = (
        cost.spec,
        cost.kind,
        cost.op,
        cost.input_grades,
        cost.left_grades,
        cost.right_grades,
        cost.output_grades,
        cost.max_lanes,
        cost.pair_count,
    )
    if key in _WARNED_PLAN_COSTS:
        return
    _WARNED_PLAN_COSTS.add(key)
    warnings.warn(
        f"Static {cost.kind} plan for {cost.op} is large: {detail}.",
        RuntimeWarning,
        stacklevel=3,
    )
